language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  on:
    tags: true
  provider: pypi
  user:
    secure: HbtOw27X00utwP31MNx1vDDRBT/7FcyMYcCCL0kkQ0nYevBlPXxrggZP197balJaRK5ONjcCFCwLgg5K2x81K4TJlByOFXw4PyPyPgS8LiATrAhDTNtH7fQ5OGt3NbfXYs6qrB/amQ2RM1SrtHh+YxT40ETO5JxFsTk28/FO33sA+SGCFwHV1daLOQToqwNn/EeQS1nEekIV9VXnXOykT1HXmDlIpEABMxnw9TopSVYsSnlxBEoTxQfKVioH4RcFj4KAgFewajgHxlYH4nHZGphWzRe3yeb1ngD08JG90tAaHcy2GxGpxKLFRYZvXJRrYXMyhpDmPs1PBhzEqLv+fBPrN2H0sfpYFtvvNDtjO33KgJLWcu1zspaaLoF9BZkhjlrBUTqRKMlO13prADSpgGKs9JaX51NWuZx7nLNMShr4rwrfjU/eAFCRKmeSlvgrdWB8HQQLsyjxJ0z/VSZK5AeiiCOtSKTnRUd54VTMPOzTKItzboUPNwW/FpIsN8YRaoPz/UD3JWlU/r7jZvl8XIjmw5gRDerOJZAdL8ceB9JztMY8siAx7DX7pe0ZLeqkn5H+ngw4kj2Ip3Je3i9VsP+csZy7eDLOgnNfrSVTiJU5Y/YOAKZbe375UuSVOVgKEQ04rgiopyKf+rB91qAfRRDHNZlkGNVSKdJGLAKLhBc=
  password:
    secure: BqeAm6so5mKOJJW/SDF8r0djqW7GudolaO/DwemZb+R1XbU2oxW7WWQadRZWRv8IW0bxGQHjTi2EvlyeX+Wwab3nAnrt2Q5MPFXQDO+amYSsArxYaonF2wU4ySrsOZtBCz1xMx4HLtJkEK5ybinL4i6Ibv3t/YiENtziE+nwbhMKWMBon/NIAJVGA7J6tEkgOYcy9mZsg/QFMwOwOExU1qsZ4p+4EOUMDRCS2j3nA53FbJmrIPniAFdEQHYeiqxPCvNxsMSITd1v8rBmfIRY3XAps0SEAHS1L2zIX8ZqfBJGRaYdnwsMH/Z9GTXqnbU3JP7FkevgpRqbtL1/QeijEkz/fM8kHKXqbydN9HPHouZSQSQsaQPX4uiFgnvPF7CbW1XP7mFDRKUh1X6x+jsAoFuqcbLzmpwo3w78qoe5CUxLDj+UdOxsfWNLJ4VsOhrd0YVJ6IKNzMWlTIAoD45wLSfMT8lBbJigkw/74XknBkVbM9RDObuZdks7ZD1d1jrgKWhNav+shaopP30xRzUuve2Ph1yW55SOL/uPrCbMvRj2NlJQzEM49voGPzUG/7/TsA7iN4qpHnhdAn79B+Azt7Xo4iLUNMh835w+kZGH9t/2320tLEC07n7kx+taNFKWUdj80w6QWdtMIdBsj+ealA+zWIxrL/y3bB3pKQN6iAk=
notifications:
  hipchat:
    rooms:
      secure: BS3q2pEuwwBiPA/SnDmUJl7cfyUoFUykRNq8D/vutc/oDTt865SPHyN7iAhUYy3JKbi5TxHmIhEy1cyrHrBEgddhxl9Z5OoZuqVYRNB/+2zUfXAYc3CozKQfAK3g6Qu65rHx2eSRkBdyC9P90rMkijjsIdevUIOGjpKKpQqghOrcmEJ8GByRY6evg5hNQRcjXTsOdUtsySW2v95o9ZtiaFLzsWsDaSsFOqRyOU9wqU+l08FbTvpLhLdchvesoynEPxYrvXiTjrqMoNde8Z8OHMRCoc95vGcXj5jllo8+fx5kXlFAGgJnqmfB6kLbVrVENvySQsz0J+qVwgK09DV1QPv9q3KtmkJkWSEK04Midyias2QTplnocNG2paLgj2oPkhmNvC4YrGC0CARbAh4SqdnS2z6KZDizSYCbk5a7T5hUYR7GmBVE9ddxtBNyKt6zg+SAx73P8ltuttKvpG4o8ZxE9ye+KX9C+MU3p1ITRTyuGBrMkvWp6CBsgd8KqPuA7LumCY0k2wsCFgYMbYdvo+u9JXfbJhlxNU17hdh7mVIDy/GnP/xhlcYJ1P4mcRkinDeonv1ZYLPDaN1z3Lrj+7d3HHn4/6qiAbEpj2lS2NqZuGNwSiaCN7Gpc8fFQhhmEsPROs8MBIMu4+hZLdACK3nUCavMoL8sMxTMA2/mX3k=
